name: run autobuild
on:
  schedule:
    - cron: '2 2 * * 2'
  workflow_dispatch:
jobs:
  autobuild-sh:
    runs-on: ubuntu-latest
    name: run autobuild
    steps:
      - name: checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.OTHER_TOKEN }}
      - name: run autobuild
        shell: bash
        run: |
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          ./autobuild.py
